development:
  adapter: postgresql
  encoding: utf-8
  database: vizadapt_development
  pool: 5
  username:
  password:

test: &test
  adapter: postgresql
  encoding: utf-8
  database: vizadapt_test
  pool: 5
  username:
  password: